[build]
  publish = "."

# Default root render
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Clean /thank-you path (optional)
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200
